### ISSUE TITLE
addon is not working with plf 4.3.1 and plf 4.4.0-RC03

### ISSUE THREAD

**Issue by rdenarie** [exo-addons/jmxtrans-addon#1]
Hello,
The addon is not working on plf 4.3.1 and PLF 4.4.0-RC03

In   fact, since the upgrade of embedded-jmx to 1.1.3, there is a dependency problem : 
2016-12-13 16:36:15,301 | ERROR | Exception sending context initialized event to listener instance of class org.exoplatform.addons.jmxtrans.JMXTransLoaderListener [o.a.c.c.C.[.[.[.0.0-SNAPSHOT]<localhost-startStop-5>] 
java.lang.NoClassDefFoundError: org/apache/commons/pool2/KeyedPooledObjectFactory
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_111]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_111]
	at org.jmxtrans.embedded.config.ConfigurationParser.parseOutputWritersNode(ConfigurationParser.java:233) ~[embedded-jmxtrans-1.1.3.jar:na]
	at org.jmxtrans.embedded.config.ConfigurationParser.mergeEmbeddedJmxTransConfiguration(ConfigurationParser.java:193) ~[embedded-jmxtrans-1.1.3.jar:na]
	at org.jmxtrans.embedded.config.ConfigurationParser.mergeEmbeddedJmxTransConfiguration(ConfigurationParser.java:139) ~[embedded-jmxtrans-1.1.3.jar:na]
	at org.jmxtrans.embedded.config.ConfigurationParser.mergeEmbeddedJmxTransConfiguration(ConfigurationParser.java:112) ~[embedded-jmxtrans-1.1.3.jar:na]
	at org.jmxtrans.embedded.config.ConfigurationParser.newEmbeddedJmxTrans(ConfigurationParser.java:81) ~[embedded-jmxtrans-1.1.3.jar:na]
	at org.exoplatform.addons.jmxtrans.JMXTransLoaderListener.contextInitialized(JMXTransLoaderListener.java:72) ~[jmxtrans-addon-lib-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118) [catalina.jar:7.0.72]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875) [catalina.jar:7.0.72]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.72]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092) [catalina.jar:7.0.72]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984) [catalina.jar:7.0.72]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool2.KeyedPooledObjectFactory
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892) ~[catalina.jar:7.0.72]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735) ~[catalina.jar:7.0.72]
	... 21 common frames omitted
2016-12-13 16:36:15,301 | ERROR | One or more listeners failed to start. Full details will be found in the appropriate container log file [org.apache.catalina.core.StandardContext<localhost-startStop-5>] 
2016-12-13 16:36:15,302 | ERROR | Context [/jmxtrans-addon-webapp-1.0.0-SNAPSHOT] startup failed due to previous errors [org.apache.catalina.core.StandardContext<localhost-startStop-5>] 
2016-12-13 16:36:15,303 | INFO  | Stop embedded-jmxtrans ... [o.a.c.c.C.[.[.[.0.0-SNAPSHOT]<localhost-startStop-5>] 
2016-12-13 16:36:15,303 | ERROR | Silently skip exception unregistering mbean 'null' [o.e.a.jmxtrans.JMXTransLoaderListener<localhost-startStop-5>] 
2016-12-13 16:36:15,305 | ERROR | Exception sending context destroyed event to listener instance of class org.exoplatform.addons.jmxtrans.JMXTransLoaderListener [o.a.c.c.C.[.[.[.0.0-SNAPSHOT]<localhost-startStop-5>] 
org.jmxtrans.embedded.EmbeddedJmxTransException: Exception stopping 'null'
	at org.exoplatform.addons.jmxtrans.JMXTransLoaderListener.contextDestroyed(JMXTransLoaderListener.java:100) ~[jmxtrans-addon-lib-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5165) [catalina.jar:7.0.72]
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5829) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:149) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875) [catalina.jar:7.0.72]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.72]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092) [catalina.jar:7.0.72]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984) [catalina.jar:7.0.72]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.NullPointerException: null
	at org.exoplatform.addons.jmxtrans.JMXTransLoaderListener.contextDestroyed(JMXTransLoaderListener.java:98) ~[jmxtrans-addon-lib-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	... 14 common frames omitted

embedded-jmxtrans needs org.apache.commons:commons-pool2:2.3 instead of commons-pool:commons-pool:1.6 which is present in PLF.
